function Hd = bandpass_hb
%BANDPASS_HB 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13.
% Generated on: 22-Apr-2022 20:41:54

% Chebyshev Type II Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 200;  % Sampling Frequency
% 0.8,1.0,2.8,3.0
Fstop1 = 0.8;         % First Stopband Frequency
Fpass1 = 1.0;         % First Passband Frequency
Fpass2 = 2.8;         % Second Passband Frequency
Fstop2 = 3.0;         % Second Stopband Frequency
Astop1 = 80;          % First Stopband Attenuation (dB)
Apass  = 1;           % Passband Ripple (dB)
Astop2 = 80;          % Second Stopband Attenuation (dB)
match  = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
Hd = design(h, 'cheby2', 'MatchExactly', match);

% [EOF]
